"""add UserMixin module

Revision ID: b480cfb76d54
Revises: 94eea039b463
Create Date: 2016-11-28 15:58:35.952416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b480cfb76d54'
down_revision = '94eea039b463'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('email', table_name='users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    ### end Alembic commands ###
